# Generated by Django 5.2.4 on 2025-08-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_kyc_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="KYCProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("supports_documents", models.BooleanField(default=True)),
                ("supports_biometric", models.BooleanField(default=False)),
                ("supports_pep", models.BooleanField(default=False)),
                ("supports_brazil", models.BooleanField(default=True)),
                (
                    "cost_per_document",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Custo por documento (BRL)",
                        max_digits=8,
                    ),
                ),
                (
                    "cost_per_biometric",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Custo adicional por biometria (BRL)",
                        max_digits=8,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "beta_only",
                    models.BooleanField(
                        default=False, help_text="Disponível apenas para usuários beta"
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=50, help_text="Prioridade no roteamento (0-100)"
                    ),
                ),
                (
                    "max_daily_volume",
                    models.PositiveIntegerField(
                        default=1000, help_text="Limite diário de verificações"
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveIntegerField(
                        default=30, help_text="Timeout para API calls"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configurações específicas do provedor",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "KYC Provider Configuration",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="KYCProviderStats",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="Nome do provedor (stripe, idwall, unico, datavalid)",
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Total de tentativas de verificação"
                    ),
                ),
                (
                    "successes",
                    models.PositiveIntegerField(
                        default=0, help_text="Total de verificações aprovadas"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Custo total acumulado (BRL)",
                        max_digits=12,
                    ),
                ),
                (
                    "monthly_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000.0,
                        help_text="Orçamento mensal limite (BRL)",
                        max_digits=10,
                    ),
                ),
                (
                    "monthly_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Gasto no mês atual (BRL)",
                        max_digits=10,
                    ),
                ),
                (
                    "last_ms_p95",
                    models.PositiveIntegerField(
                        default=0, help_text="Latência P95 em milissegundos"
                    ),
                ),
                (
                    "pep_hits",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Quantidade de hits PEP/sanções encontrados",
                    ),
                ),
                (
                    "free_tier_limit",
                    models.PositiveIntegerField(
                        default=0, help_text="Limite gratuito mensal"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Provedor ativo para roteamento"
                    ),
                ),
                (
                    "reset_month",
                    models.DateField(
                        auto_now_add=True, help_text="Último reset mensal das métricas"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "KYC Provider Statistics",
                "verbose_name_plural": "KYC Provider Statistics",
                "ordering": ["-updated_at"],
            },
        ),
    ]
