# Generated by Django 5.2.4 on 2025-08-02 14:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_badges_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoReleaseRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=1, help_text="Maior número = maior prioridade"
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=dict, help_text="Condições que devem ser atendidas"
                    ),
                ),
                ("timeout_days", models.IntegerField(default=7)),
                (
                    "auto_approve_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("requires_manual_review", models.BooleanField(default=False)),
                ("applies_to_categories", models.JSONField(default=list)),
                ("applies_to_user_levels", models.JSONField(default=list)),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="EscrowRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "release_type",
                    models.CharField(
                        choices=[
                            ("auto", "Liberação Automática"),
                            ("manual", "Liberação Manual"),
                            ("dispute_resolution", "Resolução de Disputa"),
                            ("partial", "Liberação Parcial"),
                            ("emergency", "Liberação de Emergência"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Agendada"),
                            ("processing", "Processando"),
                            ("completed", "Concluída"),
                            ("failed", "Falhada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("approval_reason", models.TextField(blank=True)),
                ("reason", models.TextField(help_text="Razão da liberação")),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_releases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrow_releases",
                        to="api.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentDispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("quality", "Qualidade do Trabalho"),
                            ("delivery", "Prazo de Entrega"),
                            ("payment", "Problemas de Pagamento"),
                            ("communication", "Problemas de Comunicação"),
                            ("scope", "Mudança de Escopo"),
                            ("cancellation", "Cancelamento"),
                            ("fraud", "Suspeita de Fraude"),
                            ("other", "Outros"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Aberta"),
                            ("investigating", "Investigando"),
                            ("awaiting_response", "Aguardando Resposta"),
                            ("mediation", "Mediação"),
                            ("arbitration", "Arbitragem"),
                            ("resolved", "Resolvida"),
                            ("closed", "Fechada"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "resolution_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("client_favor", "Favor do Cliente"),
                            ("freelancer_favor", "Favor do Prestador"),
                            ("partial_refund", "Reembolso Parcial"),
                            ("mutual_agreement", "Acordo Mútuo"),
                            ("no_action", "Sem Ação"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "evidence_urls",
                    models.JSONField(
                        default=list, help_text="URLs dos arquivos de evidência"
                    ),
                ),
                ("client_evidence", models.JSONField(default=dict)),
                ("freelancer_evidence", models.JSONField(default=dict)),
                ("mediation_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=1, help_text="1=Baixa, 2=Média, 3=Alta, 4=Crítica"
                    ),
                ),
                (
                    "amount_disputed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_payment_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freelancer_payment_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_payment_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mediator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mediated_payment_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_disputes",
                        to="api.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disputa de Pagamento",
                "verbose_name_plural": "Disputas de Pagamento",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("pagseguro", "PagSeguro"),
                            ("mercadopago", "Mercado Pago"),
                            ("pix", "PIX"),
                            ("bank_transfer", "Transferência Bancária"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("card", "Cartão de Crédito/Débito"),
                            ("pix", "PIX"),
                            ("boleto", "Boleto Bancário"),
                            ("wallet", "Carteira Digital"),
                            ("bank_transfer", "Transferência Bancária"),
                            ("installments", "Parcelamento"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Dados específicos do método (últimos 4 dígitos, banco, etc.)",
                    ),
                ),
                (
                    "provider_payment_method_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("provider_customer_id", models.CharField(blank=True, max_length=255)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(max_length=100, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="BRL", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requires_payment_method", "Requer Método"),
                            ("requires_confirmation", "Requer Confirmação"),
                            ("requires_action", "Requer Ação"),
                            ("processing", "Processando"),
                            ("requires_capture", "Requer Captura"),
                            ("canceled", "Cancelado"),
                            ("succeeded", "Sucedido"),
                        ],
                        max_length=30,
                    ),
                ),
                ("client_secret", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "application_fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("transfer_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_intent",
                        to="api.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.paymentmethod",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StripeAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stripe_account_id", models.CharField(max_length=100, unique=True)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("express", "Express"),
                            ("custom", "Custom"),
                            ("standard", "Standard"),
                        ],
                        default="express",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("verified", "Verificada"),
                            ("restricted", "Restrita"),
                            ("rejected", "Rejeitada"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("capabilities", models.JSONField(default=dict)),
                ("requirements", models.JSONField(default=dict)),
                ("settings", models.JSONField(default=dict)),
                ("onboarding_link", models.URLField(blank=True)),
                ("onboarding_completed", models.BooleanField(default=False)),
                (
                    "onboarding_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_webhook_at", models.DateTimeField(blank=True, null=True)),
                ("webhook_events_received", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayoutSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("daily", "Diário"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensal"),
                            ("manual", "Manual"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                (
                    "delay_days",
                    models.IntegerField(
                        default=2, help_text="Dias de delay para payout"
                    ),
                ),
                (
                    "minimum_amount",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
                ),
                ("auto_payout_enabled", models.BooleanField(default=True)),
                (
                    "max_daily_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_payout_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stripe_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_schedule",
                        to="api.stripeaccount",
                    ),
                ),
            ],
        ),
    ]
