version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET=dev-secret-key
      - DATABASE_URL=postgresql://marketplace:password@postgres:5432/marketplace_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - ELASTIC_HOST=http://opensearch:9200
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres
      - redis
      - opensearch

  postgres:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_DB=marketplace_db
      - POSTGRES_USER=marketplace
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - opensearch_data:/usr/share/opensearch/data

  celery:
    build: .
    command: celery -A marketplace worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET=dev-secret-key
      - DATABASE_URL=postgresql://marketplace:password@postgres:5432/marketplace_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - ELASTIC_HOST=http://opensearch:9200
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres
      - redis
      - opensearch

volumes:
  postgres_data:
  opensearch_data: